tools:
    php_code_sniffer:
        config:
            standard: "PSR2"
filter:
    excluded_paths:
        - tests/*
build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'php-clover'
